rules:
  no-css-comments: 0
  placeholder-in-extend: 0
  nesting-depth: 0
  property-sort-order:
    - 1
    -
      order: concentric
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
  no-vendor-prefixes:
      - 1
      - ignore-non-standard: true
  no-misspelled-properties:
    - 1
    -
      extra-properties: overflow-scrolling
